name: Bug Report
description: Something is crashing or not working as expected.
title: "[Bug]: "
projects: ["AsherGlick/Burrito"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: burrito_version
    attributes:
      label: Burrito Version
      description: Please make sure you are using the latest version of Burrito before opening a report.
      options:
        - label: I can reproduce my problem with the latest available release.
          required: true
  - type: dropdown
    id: burrito_link_install_method
    attributes:
      label: Burrito Link
      description: How did you install burrito link?
      options:
        - DLL (d3d11.dll)
        - DLL (arcdps_burritolink.dll)
        - Standalone (burrito_link.exe)
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what is wrong!
      value: "A bug happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        The following information is optional, but it will help us alot if you provide as much as possible.
        If you are comfortable using a command line, please run the given commands and copy-paste the output.
        (This will be automatically formatted into code, so no need for backticks.)
  - type: textarea
    id: compositors
    attributes:
      label: Compositors
      description: |
        What compositor does your system use?
        Please run the command `inxi -Gxxx` or answer in your own words.
      render: shell
  - type: textarea
    id: window_managers
    attributes:
      label: Window Managers
      description: |
        What window manager does your system use?
        Please run the command `wmtrl -m` or answer in your own words.
      render: shell
 - type: textarea
    id: display_protocol
    attributes:
      label: Display Protocol
      description: |
        What display protocol does your system use?
        Please run the command `echo $XDG_SESSION_TYPE` or answer in your own words.
      render: shell
